services:
  scootin-simulator:
    build:
      context: .
      dockerfile: Dockerfile.simulator
    container_name: scootin-simulator
    env_file:
      - .env
    environment:
      - SIMULATOR_SERVER_URL=${SIMULATOR_SERVER_URL:-http://host.docker.internal:8080}
    restart: unless-stopped
